name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  deploymigrations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Deploy migrations
        env:
          DATABASE_URL: ${{ secrets.PROD_DB }}
        run: |
          echo "::add-mask::${{ secrets.PROD_DB }}"
          npx prisma migrate deploy
  build:
    runs-on: ubuntu-latest
    needs: deploymigrations
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yomer-api:latest
